[".config/emacs"]
    type = "git-repo"
    url = "https://github.com/Cbeck527/emacs.d.git"
    # no refresh period since I pull that often

["src/my-prompt"]
    type = "git-repo"
    url = "https://github.com/Cbeck527/my-prompt.git"
    # no refresh period since I pull that often

[".local/share/tree-sitter/tree-sitter-elisp"]
    type = "git-repo"
    url = "https://github.com/Wilfred/tree-sitter-elisp.git"
    refreshPeriod = "168h" # 7 days

[".config/tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
    refreshPeriod = "720h" # 30 days

[".vim/bundle/Vundle.vim"]
    type = "git-repo"
    url = "https://github.com/VundleVim/Vundle.vim.git"
    refreshPeriod = "720h" # 30 days
