k9s:
  liveViewAutoRefresh: true
  screenDumpDir: /Users/christopher.becker/Downloads/k9s-screen-dumps
  refreshRate: 2
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: false
  skipLatestRevCheck: false
  disablePodCounting: false
  ui:
    enableMouse: false
    logoless: true
    reactive: true
  shellPod:
    image: debian:bookworm-slim
    namespace: default
    limits:
      cpu: 100m
      memory: 256Mi
  imageScans:
    enable: false
    exclusions:
      namespaces: []
      labels: {}
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
    textWrap: false
    showTime: false
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
